# Generated by Django 5.1.6 on 2025-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_userprofile_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("firebase_id", models.CharField(max_length=100, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
